spring:
  application:
    name: third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key:
      secret-key:
      oss:
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: hxqmall
server:
  port: 3008
